version: '3'
services:
  composer-install:
    build: ./composer
    volumes:
      - ./html:/html
      - ./config/composer/auth.json:/root/.composer/auth.json
  web:
    image: nginx:1.12
    ports: 
      - 80:80
    volumes:
      - ./html:/var/www/html
      - ./config/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    depends_on:
      - composer-install
      - php
  php:
    build: ./php
    volumes:
      - ./html:/var/www/html
    links:
      - db
    depends_on:
      - composer-install
      - db
  db:
    image: mysql:5.7.28
    volumes:
      - ./db/data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    depends_on:
      - composer-install
  elasticsearch:
    image: elasticsearch:6.8.4
    depends_on:
      - composer-install
  redis:
    image: "redis:alpine"
