version: '3'
services:
  composer-install:
    build: ./composer
    volumes:
      - ./html:/html:delegated
      - ./config/composer/auth.json:/root/.composer/auth.json
  varnish:
    image: varnish:6.4
    # ports:
    #   - 80:80
    links:
      - nginx
  nginx:
    image: nginx:1.12
    ports: 
      - 80:80
    volumes:
      - ./html:/var/www/html:delegated
      - ./config/nginx/magento.conf:/etc/nginx/conf.d/default.conf:cached
    links:
      - php
    depends_on:
      - php
  php:
    build: ./php
    volumes:
      - ./html:/var/www/html:delegated
    links:
      - db
      - redis-cache
      - redis-sessions
      - elasticsearch
    depends_on:
      - db
  db:
    image: mysql:5.7.31
    volumes:
      - ./db/data:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
  elasticsearch:
    image: elasticsearch:7.9.0
    environment:
      - discovery.type=single-node
  redis-cache:
    image: redis:alpine
  redis-sessions:
    image: redis:alpine
